development:
  adapter: postgresql
  encoding: unicode
  database: dbar5qhociika1
  pool: 5
  username: emcezstxvdlvlb
  password: NCWZY8EzbYzT7q7t1CC2DWkzjH
  host: ec2-107-22-169-148.compute-1.amazonaws.com

test:
  adapter: postgresql
  encoding: unicode
  database: dbar5qhociika1
  pool: 5
  username: emcezstxvdlvlb
  password: NCWZY8EzbYzT7q7t1CC2DWkzjH
  host: ec2-107-22-169-148.compute-1.amazonaws.com

 production:
  adapter: postgresql
  encoding: unicode
  database: dbar5qhociika1
  pool: 5
  username: emcezstxvdlvlb
  password: NCWZY8EzbYzT7q7t1CC2DWkzjH
  host: ec2-107-22-169-148.compute-1.amazonaws.com   